# Generated by Django 2.2.5 on 2019-09-07 21:30

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrashImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('image', models.TextField()),
                ('trash_density', models.DecimalField(decimal_places=8, max_digits=16)),
                ('google_ml_json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('time_taken', models.DateField(blank=True, default=None, null=True)),
                ('before_after_cleaning', models.BooleanField()),
                ('description', models.CharField(max_length=150)),
            ],
        ),
    ]
