# Generated by Django 2.2.5 on 2019-09-08 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trash_api', '0002_alttrashimagemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AltTrashImageModel',
        ),
        migrations.RemoveField(
            model_name='trashimagemodel',
            name='location',
        ),
    ]
