# Generated by Django 2.2.5 on 2019-09-08 00:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trash_api', '0003_auto_20190908_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashimagemodel',
            name='location',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'empty': 'empty'}),
            preserve_default=False,
        ),
    ]
